### ISSUE TITLE
Troubles with Blinker library

### ISSUE THREAD

**Issue by kerat71** [viperet/esp8266-power-monitor#8]
Hi, thanks for sharing this project. I have difficulties to compile it. Please would you specify Blinker library version and from where to download it?
Greetings,
Milen

**Comment by viperet** [comment]
@kerat71 I used Blinker v1.0.3 from https://github.com/MajenkoLibraries/Blinker
Libraries are installed automatically by PlatformIO

**Comment by kerat71** [comment]
Thank you for answering me, there is so many blinker libraries out there and what you use is not in a first 10 searched. I decided that this https://github.com/blinker-iot/blinker-library is the one and I have so many troubles.
